
# EVENT_DATA_TYPES = {
# GAME_ID 
# AWAY_TEAM_ID DET
# INN_CT 1.0
# BAT_HOME_ID 0.0
# OUTS_CT 0.0
# BALLS_CT 2.0
# STRIKES_CT 2.0
# PITCH_SEQ_TX BCSFBX
# AWAY_SCORE_CT 0.0
# HOME_SCORE_CT 0.0
# BAT_ID philt001
# BAT_HAND_CD ?
# RESP_BAT_ID philt001
# RESP_BAT_HAND_CD ?
# PIT_ID abboj001
# PIT_HAND_CD ?
# RESP_PIT_ID abboj001
# RESP_PIT_HAND_CD ?
# POS2_FLD_ID stanm002
# POS3_FLD_ID mattd001
# POS4_FLD_ID kellp001
# POS5_FLD_ID boggw001
# POS6_FLD_ID gallm001
# POS7_FLD_ID polol001
# POS8_FLD_ID willb002
# POS9_FLD_ID oneip001
# BASE1_RUN_ID 
# BASE2_RUN_ID 
# BASE3_RUN_ID 
# EVENT_TX E6/TH/G6.B-1
# LEADOFF_FL T
# PH_FL F
# BAT_FLD_CD 7.0
# BAT_LINEUP_ID 1.0
# EVENT_CD 18.0
# BAT_EVENT_FL T
# AB_FL T
# H_CD 0.0
# SH_FL F
# SF_FL F
# EVENT_OUTS_CT 0.0
# DP_FL F
# TP_FL F
# RBI_CT 0.0
# WP_FL F
# PB_FL F
# FLD_CD 6.0
# BATTEDBALL_CD G
# BUNT_FL F
# FOUL_FL F
# BATTEDBALL_LOC_TX 6
# ERR_CT 1.0
# ERR1_FLD_CD 6.0
# ERR1_CD T
# ERR2_FLD_CD 0.0
# ERR2_CD N
# ERR3_FLD_CD 0.0
# ERR3_CD N
# BAT_DEST_ID 1.0
# RUN1_DEST_ID 0.0
# RUN2_DEST_ID 0.0
# RUN3_DEST_ID 0.0
# BAT_PLAY_TX 
# RUN1_PLAY_TX 
# RUN2_PLAY_TX 
# RUN3_PLAY_TX 
# RUN1_SB_FL F
# RUN2_SB_FL F
# RUN3_SB_FL F
# RUN1_CS_FL F
# RUN2_CS_FL F
# RUN3_CS_FL F
# RUN1_PK_FL F
# RUN2_PK_FL F
# RUN3_PK_FL F
# RUN1_RESP_PIT_ID 
# RUN2_RESP_PIT_ID 
# RUN3_RESP_PIT_ID 
# GAME_NEW_FL T
# GAME_END_FL F
# PR_RUN1_FL F
# PR_RUN2_FL F
# PR_RUN3_FL F
# REMOVED_FOR_PR_RUN1_ID 
# REMOVED_FOR_PR_RUN2_ID 
# REMOVED_FOR_PR_RUN3_ID 
# REMOVED_FOR_PH_BAT_ID 
# REMOVED_FOR_PH_BAT_FLD_CD 0.0
# PO1_FLD_CD 0.0
# PO2_FLD_CD 0.0
# PO3_FLD_CD 0.0
# ASS1_FLD_CD 0.0
# ASS2_FLD_CD 0.0
# ASS3_FLD_CD 0.0
# ASS4_FLD_CD 0.0
# ASS5_FLD_CD 0.0
# HOME_TEAM_ID NYA
# BAT_TEAM_ID DET
# FLD_TEAM_ID NYA
# BAT_LAST_ID 0.0
# INN_NEW_FL T
# INN_END_FL F
# START_BAT_SCORE_CT 0.0
# START_FLD_SCORE_CT 0.0
# INN_RUNS_CT 0.0
# GAME_PA_CT 0.0
# INN_PA_CT 0.0
# PA_NEW_FL T
# PA_TRUNC_FL F
# START_BASES_CD 0.0
# END_BASES_CD 1.0
# BAT_START_FL T
# RESP_BAT_START_FL T
# BAT_ON_DECK_ID samuj001
# BAT_IN_HOLD_ID frymt001
# PIT_START_FL T
# RESP_PIT_START_FL T
# RUN1_FLD_CD 0.0
# RUN1_LINEUP_CD 0.0
# RUN1_ORIGIN_EVENT_ID 0.0
# RUN2_FLD_CD 0.0
# RUN2_LINEUP_CD 0.0
# RUN2_ORIGIN_EVENT_ID 0.0
# RUN3_FLD_CD 0.0
# RUN3_LINEUP_CD 0.0
# RUN3_ORIGIN_EVENT_ID 0.0
# RUN1_RESP_CAT_ID 
# RUN2_RESP_CAT_ID 
# RUN3_RESP_CAT_ID 
# PA_BALL_CT 2.0
# PA_CALLED_BALL_CT 2.0
# PA_INTENT_BALL_CT 0.0
# PA_PITCHOUT_BALL_CT 0.0
# PA_HITBATTER_BALL_CT 0.0
# PA_OTHER_BALL_CT 0.0
# PA_STRIKE_CT 4.0
# PA_CALLED_STRIKE_CT 1.0
# PA_SWINGMISS_STRIKE_CT 1.0
# PA_FOUL_STRIKE_CT 1.0
# PA_INPLAY_STRIKE_CT 1.0
# PA_OTHER_STRIKE_CT 0.0
# EVENT_RUNS_CT 0.0
# FLD_ID gallm001
# BASE2_FORCE_FL F
# BASE3_FORCE_FL F
# BASE4_FORCE_FL F
# BAT_SAFE_ERR_FL T
# BAT_FATE_ID 0.0
# RUN1_FATE_ID 0.0
# RUN2_FATE_ID 0.0
# RUN3_FATE_ID 0.0
# FATE_RUNS_CT 0.0
# ASS6_FLD_CD 0.0
# ASS7_FLD_CD 0.0
# ASS8_FLD_CD 0
# ASS9_FLD_CD 0.0
# ASS10_FLD_CD 0.0
# UNKNOWN_OUT_EXC_FL F
# UNCERTAIN_PLAY_EXC_FL F
