name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # TODO can be re-enabled once new builds are stable
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os:
          - ubuntu-22.04
        include:
          # Test older/EoL python versions on ubuntu-20.04
          # Ubuntu 22.04 comes with OpenSSL 3.0, so only CPython 3.9+ is compatible with it
          # https://github.com/python/cpython/issues/83001
          - python-version: "3.6"
            os: ubuntu-20.04
          - python-version: "3.7"
            os: ubuntu-20.04
          #- python-version: "3.8"
          #  os: ubuntu-20.04
        exclude:
          # FIXME disable versions >=3.8 until builds are fixed for those versions
          #- python-version: "3.9"
          - python-version: "3.10"
          - python-version: "3.11"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test

